version: '3.3'

# Container for Web Handler

services:
  $CNTR_FRONT:
    env_file:
      - .env
    build: 
      context: ./Dockerfiles
      dockerfile: dockerfile-nginx
      args:
        - WEB_ADDRESS=${WEB_ADDRESS}
        - REPO_LINK=${REPO_LINK}
        - REPO_BRANCH=${REPO_BRANCH}
        - REPO_PROJECT_FOLDER=${REPO_PROJECT_FOLDER}
        - CNTR_BACK=${CNTR_BACK}
        - CNTR_DB=${CNTR_DB}
        - APP_DB=${APP_DB}
        - APP_DB_USER=${APP_DB_USER}
        - APP_DB_PASS=${APP_DB_PASS}
    image: glue-frontend
    contaner_name: glue-frontend
    restart: unless-stopped
    working_dir: /public_html
    volumes:
      - glue-app:/public_html
    ports:
      - 80:80
    network:
      - glue

